services:
  web:
    build:
      context: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672//
  worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A django_project worker --loglevel=info
    volumes:
      - ./DjangoForProfessionals:/app
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  postgres_data: